dist: xenial
language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install pylint flake8

stages:
  - lint
  - name: build python package
    if: branch != master || type != push

jobs:
  include:
    - stage: lint
      script:
        - pylint ./*.py ./gramhopper
        - flake8
    - stage: build package
      script:
        - python setup.py sdist bdist_wheel
