dist: xenial
language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install pylint flake8 pytype

stages:
  - lint

  - name: build
    if: (branch != master && tag IS blank) || type != push

  - name: deploy docker image
    if: (branch = master || tag IS present) && type = push

jobs:
  include:
    - stage: lint
      script:
        - pylint ./*.py ./gramhopper
        - flake8
        - pytype  --config ./setup.cfg -V $TRAVIS_PYTHON_VERSION ./*.py ./gramhopper
    - stage: build
      script:
        - python setup.py sdist bdist_wheel
        - docker build -t $DOCKER_IMAGE_NAME .
    - stage: deploy docker image
      script:
        - |
          if [ ! -z "$TRAVIS_TAG" ]; then
            export IMAGE_TAG=$TRAVIS_TAG
          else
            export IMAGE_TAG='latest'
          fi
        - docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
